# tasks file for wordpress
---
- name: Restart php-fpm before WordPress installation, in all cases
  service:
    name: "{{php_fpm_daemon}}"
    state: restarted

- name: Restart service httpd, in all cases
  service:
    name: apache2
    state: restarted

- name: Remove old files for WordPress
  file:
    path: /tmp/wordpress
    state: absent

- name: Remove old files for PostgreSQL
  file:
    path: /tmp/git
    state: absent

- name: Download WordPress
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/tmp/ copy=no
  become: yes


- name: Stat wordpress installation
  stat: path=/var/www/html/wordpress
  register: wordpress_exist

- name: Copy wordpress to root dir
  command: cp -r /tmp/wordpress /var/www/html/
  when: wordpress_exist.stat.exists == False

- name: Clone module for PostgreSQL support
  become: yes
  git:
    repo: 'https://github.com/kevinoid/postgresql-for-wordpress.git'
    dest: /tmp/git




- name: Move Postgres module to pg4wp dir
  command: mv /tmp/git/pg4wp /var/www/html/wordpress/wp-content/pg4wp creates=/var/www/html/wordpress/wp-content/pg4wp
  become: yes
  tags: ck


- name: Move Postgres module to pg4wp dir
  command: cp /var/www/html/wordpress/wp-content/pg4wp/db.php /var/www/html/wordpress/wp-content/db.php
  become: yes

- name: Copy sample config file
  command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php creates=/var/www/html/wordpress/wp-config.php
  become: yes

- name: Update WordPress config file
  lineinfile:
    dest=/var/www/html/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define('DB_NAME', '{{postgres_db}}');"}        
    - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define('DB_USER', '{{postgres_user}}');"}        
    - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define('DB_PASSWORD', '{{postgres_pwd}}');"}
  become: yes
  tags: ck

